### PR TITLE
feat: allow to use any configured engine to replay tracking logs

### PR DESCRIPTION
**Pull request by Ian2012**
**Description:** This PR uses the already configured backends to replay tracking logs

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by mphilbrick211** [comment]
Hi @Ian2012! Just checking in to see if this PR is still in progress?

**Comment by Ian2012** [comment]
@mphilbrick211 Yes, once this PR is merged https://github.com/openedx/tutor-contrib-aspects/pull/610 I will take care of updating this PR.

**Review by bmtcril — APPROVED** [review]
Nice, I've been meaning to get back to that for a while. Thanks for knocking it out

**Comment by openedx-webhooks** [comment]
@Ian2012 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/event-routing-backends&entry.867055334=https://github.com/openedx/event-routing-backends/pull/362&entry.1484655318=https://github.com/Ian2012&entry.752974735=2023-10-27+19:21&entry.1917517419=2024-03-22+20:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
