### PR TITLE
fix: Divide by 0 errors on problem interaction events

### PR DESCRIPTION
**Pull request by bmtcril**
**Description:** Some fields in the wild have unexpected 0 values, leading to "divide by 0" errors on transform. This PR handles them somewhat more elegantly.

Closes: #311

### CODE REVIEW

**Review by Ian2012 — APPROVED** [review]
LGTM

**Comment by bmtcril** [comment]
@ziafazal can you take a peek when you have a sec? @pomegranited heads up on this one too.

**Review by pomegranited — APPROVED** [review]
LGTM 👍

**Review by ziafazal — APPROVED** [review]
LGTM

**Pull request merged**
