### PR TITLE
Allow event-routing-backends to be used when transforming non-openedx events

### PR DESCRIPTION
**Pull request by pomegranited**
**Description:** 

Event Routing Backends is designed to be installed with edx-platform, and the code assumes this. But we want to use ERB outside of the platform too -- it contains event transform classes and test logic which is useful when transforming non-openedx events.

This PR:
* Catches ImportErrors from edx-platform to fix errors like [these](https://github.com/open-craft/openedx-completion-aggregator/actions/runs/9462018403/job/26064058779?pr=205)
* Adds a utility function to add custom events to the backend whitelists.
* Refactors transformer test mixin classes to make them available for use outside of ERB.

See https://github.com/open-craft/openedx-completion-aggregator/pull/205 for an example usage.

**JIRA:** [FAL-3766](https://tasks.opencraft.com/browse/FAL-3766) (private-ref)

Part of https://github.com/openedx/openedx-aspects/issues/222

**Merge deadline:** end of June

**Testing instructions:**

See https://github.com/open-craft/openedx-completion-aggregator/pull/205 for manual test instructions.

**Merge checklist:**
- [ ] All reviewers approved
- [x] CI build is green
- [x] Version bumped
- [x] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by Ian2012 — APPROVED** [review]
For our use case, we were copying the `mock_helpers` function to other packages to be able to extend this. This looks good to me

**Comment by pomegranited** [comment]
Thank you for your review @Ian2012 !

@bmtcril or @ziafazal is there anything else I need to fix here before this can be merged?

**Review by ziafazal — APPROVED** [review]
LGTM 👍

**Review by bmtcril — APPROVED** [review]
👍 👍

**Comment by openedx-webhooks** [comment]
@pomegranited 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/event-routing-backends&entry.867055334=https://github.com/openedx/event-routing-backends/pull/431&entry.1484655318=https://github.com/pomegranited&entry.752974735=2024-06-12+02:04&entry.1917517419=2024-06-20+16:36&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
