### PR TITLE
Fix github url strings (org edx -> openedx)

### PR DESCRIPTION
**Pull request by sarina**
## This PR was autogenerated

This pr replaces the old GitHub organization, github.com/edx, with the new GitHub organization, github.com/openedx.

Tagging @openedx/tcril-engineering for review, but others are welcome to provide review.

Ref: https://github.com/openedx/tcril-engineering/issues/42

### CODE REVIEW

**Comment by sarina** [comment]
@UsamaSadiq or @awais786 could you help me out?

The docs build fails intermittently ([one build](https://github.com/openedx/event-routing-backends/runs/8309659628?check_suite_focus=true) and a [second build](https://github.com/openedx/event-routing-backends/runs/8287858078?check_suite_focus=true)).

If the docs build succeeds, I get a failure in Codecov stating `{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}`

[build a](https://github.com/openedx/event-routing-backends/runs/8309238050?check_suite_focus=true), [build b](https://github.com/openedx/event-routing-backends/runs/8309183661?check_suite_focus=true), [build c](https://github.com/openedx/event-routing-backends/runs/8309238050?check_suite_focus=true). 

It doesn't make sense that these builds are failing based on the changes I made. Are these tests super flaky?

**Comment by awais786** [comment]
@sarina There is minor issue in `rst` file. I pushed the changes.

**Comment by sarina** [comment]
Interesting, thank you. Is there anything else I need for approval?

**Review by ziafazal — APPROVED** [review]
👍

**Pull request merged**
